### ISSUE TITLE
Expose binary sensor entities for booleans

### ISSUE THREAD

**Issue by sethiele** [marcelwestrahome/home-assistant-niu-component#34]
Please change the [device Class](https://www.home-assistant.io/integrations/binary_sensor/#device-class) of the following sensor values to the right class.
I'm not a python developer so I can understand the code but can't change it. But I hope I found the right code lines.

1. `sensor.niu_scooter_$NAME_isconnected`
Type: binary Sensor
device_class: `connectivity`
https://github.com/marcelwestrahome/home-assistant-niu-component/blob/62d6386859c8c9da9a8cb81285839d7fa9246c73/custom_components/niu/sensor.py#L100
2. `sensor.niu_scooter_$NAME_ischarging`
Type: binary Sensor
device_class: `battery_charging`
https://github.com/marcelwestrahome/home-assistant-niu-component/blob/62d6386859c8c9da9a8cb81285839d7fa9246c73/custom_components/niu/sensor.py#L156
3. `sensor.niu_scooter_$NAME_islocked`
Type: binary Sensor
device_class: `lock`
https://github.com/marcelwestrahome/home-assistant-niu-component/blob/62d6386859c8c9da9a8cb81285839d7fa9246c73/custom_components/niu/sensor.py#L164

Thanks

**Comment by marcelwestrahome** [comment]
Why do you want to change this ?

**Comment by syssi** [comment]
Please keep in mind: This isn't an easy task and will be a breaking change. I will try to describe the required steps to be able to register `binary_sensor` entities:

1. Move the platform schema from `sensors.py` to `__init__.py`. So we can load & setup the platform like this:

```
niu:
  username: user@example.com
  password: mysecretpassword
  country: 49
  scooter_id: 0
```

2. Introduce a `DataUpdateCoordinator` to retrieve the data from the API endpoints once and distribute these data to all entities (`sensor` and `binray_sensor`).

This is the preliminary work that is necessary to be able to register `binary_sensor`s (with boolean state). I have avoided this work until now because the the added value is low.

**Comment by sethiele** [comment]
Hi,
it follows the documentation, and it generates a better view (with better semantic) in the UI.

**Comment by azalin1975** [comment]
Just to throw in my two cents.
If you need and want any of these sensors to be binary_sensors, you could create either a template sensor or a threshold sensor. What I did was create a threshold sensor since I did not have any experience with template sensors until not so long ago. I created a threshold sensor and set the upper limit to 0,5. This way when for instance the ischarging sensor is 1, it will be above 0,5 and thus be true. When back to 0 the sensor is set to false because that is obviously lower than 0. I created these kind of sensors in HA for _ischarging, _islocked and _isconnected.

I then also decided to dig into the template sensors because I wanted to add my NIU moped/scooter on a map. So I created a template sensor like this:
``` yaml
  - sensor:
    - name: NIU MQi GT
      unique_id: niu_mqi_gt_device
      state: "{{ states('binary_sensor.niu_scooter_is_locked') }}"
      picture: /local/local-images/niu-scooter-mqi-gt.png
      attributes:
        latitude: "{{ states('sensor.niu_scooter_axelf_latitude')  }}"
        longitude: "{{ states('sensor.niu_scooter_axelf_longitude') }}"
```

Which shows me an image of the scooter/moped (taken from the NIU official website and uploaded it to my own HA to prevent any dependancies on their website structure) in the location reported by the sensors.

Now, I am fully aware you don't need to create a template sensor for this, you can justr use the _scooterconnected sensor but I wanted a custom image to appear on the map instead of the letters of the sensor name. I had no idea if I could modify the existing sensor to accomodate for this. So, if someone has a better way of doing this, I am happy to take suggestions for my configuration.
